### ISSUE TITLE
CRASH REPORT

### ISSUE THREAD

**Issue by zzz-creator** [svaaps/eaglercrafthtml-1.8#11]
Game Crashed! I have fallen and I can't get up! If this has happened more than once then please copy the text on this screen and publish it in the #debugging channel in the official Eaglercraft discord server

Join the discord server at: https://discord.gg/Ekzcgs3DKZ

Decode this crash report at: https://deev.is/tools/crash-viewer/eagler-1.5.2/

The URL to this fork's GitHub repository is: https://github.com/lax1dude/eaglercraft

java.lang.RuntimeException: (JavaScript) OperationError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel send queue is full

Error: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel send queue is full
    at d.sendPacketToRemoteClient (https://ubg100.github.io/games/eaglercraft/eagswebrtc.js:27:163)
    at src/net/lax1dude/eaglercraft/adapter/EaglerAdapterImpl2.java:4139
    at src/net/lax1dude/eaglercraft/IntegratedServerLAN.java:174
    at src/net/lax1dude/eaglercraft/IntegratedServer.java:398
    at src/net/minecraft/client/Minecraft.java:709
    at src/net/minecraft/client/Minecraft.java:667
    at src/net/lax1dude/eaglercraft/Client.java:143
    at src/net/lax1dude/eaglercraft/Client.java:84
    at src/net/lax1dude/eaglercraft/Client.java:42
    at TeaVMThread.runner (https://ubg100.github.io/games/eaglercraft/classes.js:23:404)

eaglercraft.version = "22w43a"
eaglercraft.minecraft = "1.5.2"
eaglercraft.brand = "lax1dude"
eaglercraft.username = "Developer22"

webgl.version = WebGL 2.0 (OpenGL ES 3.0 Chromium)
webgl.renderer = ANGLE (Intel, Intel(R) HD Graphics 520 (0x00001916) Direct3D11 vs_5_0 ps_5_0, D3D11)
webgl.vendor = Google Inc. (Intel)

webgl.anisotropicGlitch = true

window.eaglercraftOpts = {"container":"game_frame","assetsURI":"assets.epk","serverWorkerURI":"worker_bootstrap.js","worldsFolder":"MAIN","servers":[{"serverName":"Placeholder Server Here","serverAddress":"play.address.net","hideAddress":false}],"relays":[{"addr":"wss://relay.deev.is/","name":"lax1dude relay #1","primary":false},{"addr":"wss://relay.lax1dude.net/","name":"lax1dude relay #2","primary":true},{"addr":"wss://relay.shhnowisnottheti.me/","name":"ayunami relay #1","primary":false}],"mainMenu":{"splashes":["WebLFG!","eaglerenophile!","You Eagler!","red fish blue fish","one fish two fish",":>","Playing from WebLFG"],"eaglerLogo":false}}

window.navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
window.navigator.vendor = Google Inc.
window.navigator.language = en-US
window.navigator.hardwareConcurrency = 4
window.navigator.deviceMemory = 8
window.navigator.platform = Win32
window.navigator.product = Gecko

rootElement.clientWidth = 1920
rootElement.clientHeight = 953
window.innerWidth = 1920
window.innerHeight = 953
window.outerWidth = 1920
window.outerHeight = 1040
window.devicePixelRatio = 1
window.screen.availWidth = 1920
window.screen.availHeight = 1040
window.screen.colorDepth = 24
window.screen.pixelDepth = 24

window.location.href = https://ubg100.github.io/games/eaglercraft/index.html

----- Begin Minecraft Config -----
CgAAAQAUc2VlbkFja25vd2xlZGdlbWVudHMBAA==
----- End Minecraft Config -----

window.minecraftServer = undefined

**Comment by zzz-creator** [comment]
@svaaps

**Comment by Daniel282-boop** [comment]
why its crashing
